language: node_js
node_js:
- '8'
matrix:
  include:
  - os: linux
  - os: osx
  - os: windows
cache:
  directories:
  - node_modules
env:
  - NODE_INSTALLER=npm
script:
- npm run make
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: out/make/*
  skip_cleanup: true
  on:
    tags: true
