language: node_js
node_js:
- '8'
os:
- linux
- osx
dist: trusty
osx_image: xcode8.3
sudo: required
cache:
  directories:
  - node_modules
env:
  matrix:
  - NODE_INSTALLER=npm
after_success:
- npm run dist
