language: node_js
node_js:
- '8'
os:
- linux
- osx
dist: trusty
osx_image: xcode8.3
sudo: required
cache:
  directories:
  - node_modules
env:
  matrix:
  - NODE_INSTALLER=npm
script:
- npm run make $TRAVIS_OS_NAME
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $TRAVIS_OS_NAME
  skip_cleanup: true
  on:
    tags: true
