language: node_js
node_js:
- '8'
matrix:
  include:
  - os: linux
    sudo: required
    addons:
      apt:
        packages:
          - fakeroot
  - os: osx
  - os: windows
cache:
  directories:
  - node_modules
env:
  - NODE_INSTALLER=npm
script:
- npm run make
deploy:
  provider: releases
  api_key: b81085d294015a236ea03e8bd310d38c14618e42
  file_glob: true
  file: out/make/*
  skip_cleanup: true
  on:
    tags: true
