language: node_js
node_js:
- '8'
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
          - fakeroot
  - os: osx
cache:
  directories:
  - node_modules
env:
  - NODE_INSTALLER=npm
script:
- npm run make
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: out/make/*
  skip_cleanup: true
  on:
    tags: true
